language: cpp

compiler:
  - gcc
  - clang


before_install:
 - sudo add-apt-repository -y ppa:gijzelaar/opencv2.4
 - sudo apt-get update -qq
 - sudo apt-get install -qq libopencv-dev
 - sudo apt-get install -qq libatlas-base-dev libeigen3-dev libsuitesparse-dev libgtest-dev
# libgoogle-glog-dev libgflags-dev


install:
 - mkdir thirdparty && cd thirdparty

# install gflags
 - curl https://gflags.googlecode.com/files/gflags-2.0-no-svn-files.tar.gz | tar xvz
 - cd gflags-2.0
 - ./configure --prefix=/usr/local
 - make -j2
 - sudo make install
 - cd ..

# install glog
 - curl https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz | tar xvz
 - cd glog-0.3.3
 - ./configure --with-gflags=/usr/local/
 - make -j2
 - sudo make install
 - cd ..

# install ceres
 - curl http://ceres-solver.org/ceres-solver-1.9.0.tar.gz | tar xvz
 - mkdir ceres-bin && cd ceres-bin
 - cmake ../ceres-solver-1.9.0
 - make -j2
# - make test
 - sudo make install
 - cd ..
 
# install thrift
 - sudo apt-get install -qq libboost-dev libboost-test-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
 - curl http://archive.apache.org/dist/thrift/0.9.2/thrift-0.9.2.tar.gz | tar zx 
 - cd thrift-0.9.2/
 - sh configure --without-csharp --without-java --without-erlang --without-nodejs --without-lua --without-python --without-perl --without-php --without-php-extension --without-ruby --without-go --without-d --without-haskell
 - make -j2 -C lib/cpp
 - sudo make install -C lib/cpp
 - cd ..

 - cd ..


script:
 -  mkdir build && cd build
 -  cmake -D CMAKE_BUILD_TYPE=Release ..
 -  make -j2
 -  make test

