language: cpp
sudo: required

#Ubuntu 16.04
dist: xenial

cache:
 - apt

compiler:
  - gcc
  - clang

env:
  - CM_ENV="-DCMAKE_BUILD_TYPE=Debug"
  - CM_ENV="-DCMAKE_BUILD_TYPE=RelWithDebInfo"
  - CM_ENV="-DCMAKE_BUILD_TYPE=Release"


install:
 - sudo apt-get install -qq cmake clang g++ libatlas-base-dev libeigen3-dev libsuitesparse-dev libgtest-dev libgflags-dev libgoogle-glog-dev libceres-dev
 - $CXX --version; $CC --version
 - "cd /usr/src/gtest && sudo cmake $CM_ENV . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
 - sudo ln -s /usr/include/eigen3/Eigen/ /usr/include/Eigen

#install openCV
 - sudo add-apt-repository ppa:xqms/opencv-nonfree -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libopencv-dev libopencv-nonfree-dev


 - mkdir thirdparty && cd thirdparty

# install thrift
 - sudo apt-get install -qq libboost-dev libboost-test-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-thread-dev libevent-dev libtool flex bison pkg-config libssl-dev
 - git clone https://github.com/apache/thrift.git - b 0.10.0
 - cd thrift/;
 - mkdir cmake_build && cd cmake_build
 - cmake -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DBUILD_C_GLIB=OFF -DBUILD_JAVA=OFF -DBUILD_PYTHON=OFF $CM_ENV ..
 - make -j2
 - sudo make install
 - cd ../..

 - cd ..



script:
 - mkdir build && cd build
 - cmake $CM_ENV ..
 - make -j2
 - make test
 - sudo make install

