language: cpp

cache:
 - apt

compiler:
  - gcc
  - clang


install:
 - sudo apt-get install -qq cmake clang g++ tree libatlas-base-dev libeigen3-dev libsuitesparse-dev libgtest-dev
# libgoogle-glog-dev libgflags-dev
 - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"


 - mkdir thirdparty && cd thirdparty

# install gflags
 - curl https://gflags.googlecode.com/files/gflags-2.0-no-svn-files.tar.gz | tar xvz
 - cd gflags-2.0
 - ./configure --prefix=/usr/local
 - make -j2
 - sudo make install
 - cd ..

# install glog
 - curl https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz | tar xvz
 - cd glog-0.3.3
 - ./configure --with-gflags=/usr/local/
 - make -j2
 - sudo make install
 - cd ..

# install ceres
 - curl http://ceres-solver.org/ceres-solver-1.9.0.tar.gz | tar xvz
 - mkdir ceres-bin && cd ceres-bin
 - cmake -D BUILD_TESTING=off ../ceres-solver-1.9.0
 - make -j2
 - sudo make install
 - cd ..

# install thrift
 - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted" -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake libboost-dev libboost-test-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-thread-dev libevent-dev libtool flex bison pkg-config libssl-dev

# - curl http://archive.apache.org/dist/thrift/0.9.2/thrift-0.9.2.tar.gz | tar zx 
# - cd thrift-0.9.2/
 - git clone https://github.com/apache/thrift.git
 - cd thrift/;
 - mkdir cmake_build && cd cmake_build && cmake ..
 - make -j2
 - sudo make install
 - cd ../..

 - cd ..
 - tree

#install openCV
 - sudo add-apt-repository -y ppa:gijzelaar/opencv2.4
 - sudo apt-get update -qq
 - sudo apt-get install -qq libopencv-dev



script:
 -  mkdir build && cd build
 -  cmake -D CMAKE_BUILD_TYPE=Release ..
 -  make -j2
 -  make test

